### ISSUE TITLE
Error: Closed Before Completing Request Action host_code

### ISSUE THREAD

**Issue by Silquetoast** [anther/smashladder-desktop#3]
![image](https://user-images.githubusercontent.com/6046602/48589718-c2af1900-e90a-11e8-9ffc-49c03e2d51e0.png)

I set up SmashLadder the same way I did on my other PC with the exact same ROM... I'm not sure what is causing this error.

**Comment by anther** [comment]
[https://www.smashladder.com/guides/view/272o/melee/how-to-play-melee-online-netplay-guide-faster-melee-proj](url)
![eh3ij4m](https://user-images.githubusercontent.com/1376446/48810831-fd44f700-ecf8-11e8-9808-862671c83138.png)

Try this part of the guide and see if it fixes it!
