### ISSUE TITLE
The input line for "Join" only appears the first time you join an opponent

### ISSUE THREAD

**Issue by kevthompson** [anther/smashladder-desktop#4]
The functionality for the "Join" feature is there, but if you paste a code in once, it stays filled in but also hidden, so you have to paste the code in the old fashioned way

**Comment by anther** [comment]
Looks like something I didn't properly test!
I'll work on a fix for this.

**Comment by kevthompson** [comment]
It looks like a result of the joinClick() function in **/app/components/BuildComponent.js**.

**Comment by anther** [comment]
I think this is fixed in current builds!
