### ISSUE TITLE
I was not prepared for this

### ISSUE THREAD

**Issue by gdoenlen** [anther/smashladder-desktop#5]
Fresh install, looks like something to do with buildlist length = 0 in app/components/Builds.js. This looks like its expected behavior but not sure how to fix it.

**Comment by anther** [comment]
Could you take a screenshot of the issue, I'm not sure if this was an error message or if you weren't prepared for something ;P.

**Comment by gdoenlen** [comment]
I uninstalled, but I'll reinstall shortly and try to grab a screenshot, but specifically this looks like an error message from app/components/Builds.js line 105. It looks like it can't find any builds. 

```js
{buildList.length === 0 && (
  <div className="no_builds">I was not prepared for this</div>
)}
```

**Comment by anther** [comment]
Oh! Interesting. What's your account name on SmashLadder? My current guess is that you possibly don't have melee or project m toggled as an active game.

**Comment by gdoenlen** [comment]
yup! that seems to have done it. Thanks anther.

**Comment by anther** [comment]
Lol, thanks! Keep this issue open, it'll remind me to update the interface.

**Comment by gdoenlen** [comment]
Will do, I'd be willing to make a PR if you have an idea of what you want to update it with.

**Comment by anther** [comment]
I'm not entirely sure yet, 
I think there's three options...
1. just link to the preference page (Laziest)
https://www.smashladder.com/account/game-preferences

2. ooorr assume the person downloaded the launcher for melee and just enable it when the user logs in..

3. Ask the person what games they want to use the launcher for and use the
https://www.smashladder.com/api/v1/ladder/ladders endpoint to update it
https://www.smashladder.com/api/v1?domain=Ladders&action=ladders

**Comment by billiegoose** [comment]
Bump! My bro was affected by this and we were very puzzled until I googled "smashladder i was not prepared for this"

**Comment by anther** [comment]
Whoops, clearly forgot about this being a thing.  Update preparing for production so that people in the future won't have to deal with this confusion ;)
