### ISSUE TITLE
Deleting last replay in replay viewer unloads the replay browser

### ISSUE THREAD

**Issue by rwendell** [anther/smashladder-desktop#6]
While deleting replays, if you delete a replay on the last page (with no other replays available), The replay module disappears. Imgur gallery for better explanation : https://imgur.com/a/kWEM1mJ . 

I was picking apart your code and I think it has to do with your `export const deleteReplay = (filePath) => (dispatch) =>` not checking to see if it is the last item on the page and then calling `const displayReplaysBasedOnCurrentPage = () => (dispatch, getState) =>` function which generates the pages, but the last page isn't available so it fails. 

I also launched your program through cmd to see if I would get any console.log() calls, but there were only the "downgrade disallowed" logs. :
`C:\Users\[My_Username]>`
`Checking for update`
`Update for version 2.3.1 is not available (latest version: 2.3.1, downgrade is disallowed).`

 I am trying to work through this, but I am not very experienced with electron/react, but hopefully this will give you a good start!

**Comment by anther** [comment]
SUPER DUPER LATE REPLY! But I think modern versions of the application at will at least cause the replay browser to reappear when new replays are generated.  Maybe it'd be good to add a placeholder to say "Replays will appear here" in the near future?
