### ISSUE TITLE
Choose Install Location

### ISSUE THREAD

**Issue by Turbo1928** [anther/smashladder-desktop#8]
I know this isn't really an issue, but it would be really nice to be able to choose where the Smashladder Launcher and different versions of Dolphin installed to. My main hard drive is almost completely full, so it was a bit of a pain to have to manually move everything out.

**Comment by anther** [comment]
https://github.com/anther/smashladder-desktop/releases/tag/v2.4.0

;).  I wrote this a while ago and haven't pushed the update yet... for some reason.

**Comment by anther** [comment]
This should be a setting for all versions 2.4.0 and above now.
